version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - app-mydb:/app/App_Data
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
  app-migration:
    build: .
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - app-mydb:/app/App_Data

volumes:
  app-mydb: